import localFont from "next/font/local";
import "./globals.css";
import Header from "./element/Header";
import Link from "next/link";
import { Facebook, Mail, MapPin, Phone } from "lucide-react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Vanilla exporte de Madagascar",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-cover bg-center`}
        style={{
          backgroundImage:
            "url('https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTA3L2pvYjE0NDgtYmFja2dyb3VuZC0wNGEteF8xLmpwZw.jpg')",
        }} // {{ edit_1 }}
      >
        <Header />
        {children}
        <footer className="bg-gray-800 text-white py-12">
          <div className="container mx-auto px-6">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              <div>
                <h3 className="text-lg font-semibold mb-4">Contactez-nous</h3>
                <ul className="space-y-2">
                  <li className="flex items-center">
                    <Phone className="h-5 w-5 mr-2" />
                    <span>+261 34 12 34 567</span>
                  </li>
                  <li className="flex items-center">
                    <Mail className="h-5 w-5 mr-2" />
                    <a href="mailto:contact@vanillemadagascar.com">
                      contact@vanillemadagascar.com
                    </a>
                  </li>
                  <li className="flex items-center">
                    <MapPin className="h-5 w-5 mr-2" />
                    <span>Sambava, Madagascar</span>
                  </li>
                </ul>
              </div>
              <div>
                <h3 className="text-lg font-semibold mb-4">Suivez-nous</h3>
                <ul className="space-y-2">
                  <li>
                    <a
                      href="#"
                      className="flex items-center hover:text-primary-light"
                    >
                      <Facebook className="h-5 w-5 mr-2" />
                      <span>Facebook</span>
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="flex items-center hover:text-primary-light"
                    >
                      <svg
                        className="h-5 w-5 mr-2"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                      >
                        <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.890-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z" />
                      </svg>
                      <span>WhatsApp</span>
                    </a>
                  </li>
                </ul>
              </div>
              <div>
                <h3 className="text-lg font-semibold mb-4">Liens rapides</h3>
                <ul className="space-y-2">
                  <li>
                    <Link href="#" className="hover:text-primary-light">
                      Accueil
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="hover:text-primary-light">
                      Produits
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="hover:text-primary-light">
                      À propos
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="hover:text-primary-light">
                      Contact
                    </Link>
                  </li>
                </ul>
              </div>
              <div>
                <h3 className="text-lg font-semibold mb-4">Documents légaux</h3>
                <ul className="space-y-2">
                  <li>
                    <Link href="#" className="hover:text-primary-light">
                      Conditions générales de vente
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="hover:text-primary-light">
                      Politique de confidentialité
                    </Link>
                  </li>
                  <li>
                    <Link href="#" className="hover:text-primary-light">
                      Mentions légales
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
            <div className="mt-8 pt-8 border-t border-gray-700 ">
              <p>
                &copy; {new Date().getFullYear()} Vanille Madagascar. Tous
                droits réservés.
              </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
