import localFont from "next/font/local";
import "./globals.css";
import Header from "./element/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Vanilla exporte de Madagascar",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-cover bg-center`}
        style={{
          backgroundImage:
            "url('https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTA3L2pvYjE0NDgtYmFja2dyb3VuZC0wNGEteF8xLmpwZw.jpg')",
        }} // {{ edit_1 }}
      >
        <div className="bg-white/60 backdrop-blur-xl">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
